name: Lint

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - uses: actions/setup-node@v1
      with:
        node-version: 12
        registry-url: https://npm.pkg.github.com/
        scope: '@biigle'

    - name: Run ESLint
      run: npm run lint
