name: Lint

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Install dependencies
      run: npm install
      env:
        NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Run ESLint
      run: npm run lint
